[package]
name = "d24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
fxhash = "0.2.1"
indicatif = { version = "0.17.9", features = ["rayon"] }
itertools = "0.14.0"
rayon = "1.10.0"
winnow = "0.6.22"
